# Use a base image with Python
FROM python:3.11-slim

# Set environment variables
ENV MKDOCS_VERSION=1.4.2

RUN apt-get update & apt-get upgrade -y

# Install MkDocs and any other required packages
RUN pip install mkdocs==${MKDOCS_VERSION} mkdocs-material

RUN pip install pillow cairosvg

RUN apt-get install libcairo2-dev

# Set the working directory inside the container
WORKDIR /docs

# Expose the port that MkDocs will run on
EXPOSE 8000

# Command to run when starting the container
CMD ["mkdocs", "serve", "-a", "0.0.0.0:8000"]